### ISSUE TITLE
Incorrect Mapping for ITI and Industry names.

### ISSUE THREAD

**Issue by aayushkedia95** [SakshamHaryana-SE/dst#36]
![Image](https://user-images.githubusercontent.com/80503666/170251797-82685b33-bf8b-401c-9c40-7dbc6473031b.png)

**Comment by ChakshuGautam** [comment]
Hey this cannot be fixed unless the data mapping is fixed. @aayushkedia95

**Comment by aayushkedia95** [comment]
@ChakshuGautam, what is the incorrect data mapping you're referring to?

**Comment by ChakshuGautam** [comment]
Either the Industry or ITI name is wrong/misspelled. Cannot see that in the image. But the test data is not correctly mapped back to the DB.

**Comment by ChakshuGautam** [comment]
Do you have the Industry and ITI that you selected. I can get back on the exact issue based on that. But is always happens when the backend is not able to find either of those. I have not added a check since I am assuming this will be fixed - don't want to do defensive coding here.

**Comment by ChakshuGautam** [comment]
Tracked here => https://github.com/SakshamHaryana-SE/dst/issues/31
